### ISSUE TITLE
Windows or Subsystem Ubuntu/OpenSuse sandbox instructions

### ISSUE THREAD

**Issue by nhudson999** [vision-dbms/vision#75]
Hello, does anyone know if there are there any sandbox install instructions or scripts for Windows?
I'm trying to get the sandbox run locally.  I can build the exes in visual studio 2019 using the .sln file provided but get the error below trying to run batchvision.
I'm also able to build the binaries on Windows Subsystem Ubuntu using the sandbox instructions but get nothing but segmentation faults when trying to run and I'm unable to figure out what memory it can't access.

>>>  Error Default Error Handler Exit  <<<
*       The Persistent Storage Manager [166]
*       A System Fault
*       Network Directory File Open [/vision/network/NDF]: 'No such file or directory'

**Comment by LeslieNewman** [comment]
I haven't played with the windows version, but this doesn't look like it relates to windows per se, but I have a bit of familiarity with the environment  (full disclosure - I'm an found of Vision and created a good deal of the application layer).  The error message indicates that Vision is trying to open a starter database located in /vision/network/NDF.  That was a very early default location for vision databases but hasn't been used in a long time.  Normally, we set an environment variable NDFPathName to reference the vision database to open as your global top level.   There are instructions in the Install.Sandbox notes that talk about these variables.  The notes use unix commands, but the intent should be the same in Windows.

**Comment by ToriHoush** [comment]
Hi - Also confirm the contents of the NDF.OSDPATH file match the directory path to the directory with the NDF file. 

so for an NDF file in /mydirectory/NDF the content of the NDF.OSDPATH should be /mydirectory/NDF

(sorry - using unix notation.  but the windows concepts are expected to work the same functionally)

**Comment by nhudson999** [comment]
Got it to work, reinstalled Ubuntu Linux distro, all good now.  Thank you all for your help.
